# Generated by Django 3.2.8 on 2021-10-25 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='activity',
        ),
        migrations.AddField(
            model_name='course',
            name='project_deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 26, 2, 0, 23, 843907)),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
