# Generated by Django 3.2.8 on 2021-10-25 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211026_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='lab_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='project_assignment_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='project_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='project_deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 26, 2, 12, 41, 715090)),
        ),
    ]
