# Generated by Django 3.2.8 on 2021-10-25 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='project_deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 26, 2, 13, 43, 749554)),
        ),
    ]
