# Generated by Django 3.2.8 on 2021-10-25 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam_points',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='lab_points',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='project_deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 26, 2, 18, 26, 316834)),
        ),
        migrations.AlterField(
            model_name='course',
            name='project_points',
            field=models.CharField(default='', max_length=200),
        ),
    ]
