# Generated by Django 3.2.8 on 2021-10-26 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20211026_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='project_assignment_title',
            new_name='project_title',
        ),
        migrations.AlterField(
            model_name='course',
            name='project_deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 26, 13, 6, 48, 953151)),
        ),
    ]
