# Generated by Django 3.2.8 on 2021-10-26 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20211026_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='exam_points',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='lab_points',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='project_deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 26, 13, 27, 48, 142256)),
        ),
        migrations.AlterField(
            model_name='course',
            name='project_points',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='project_title',
            field=models.CharField(max_length=200),
        ),
    ]
