# Generated by Django 3.2.8 on 2021-10-26 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20211026_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='project_deadline',
            field=models.DateField(default=datetime.datetime(2021, 10, 26, 15, 3, 30, 57363)),
        ),
    ]
